import { formatTime } from "../domain/time";
import type { Slot } from "../domain/generation/types";

/* Spec1.1 12.3. Answers "why is this here" by reading the trace the pipeline
   left behind, stage by stage.

   This is the single feature that makes a rule engine usable by someone who
   did not write it: without it a slot appearing at 18:07 instead of 18:00 is
   inexplicable, and the only recourse is to turn the whole layer off. */

type SlotExplainerProps = {
  slot: Slot;
  generatorName: string;
  tz: string;
  onSkipOnce: () => void;
  onSkipFuture: () => void;
  onPin: () => void;
  onReset: () => void;
  onClose: () => void;
};

const ACTION =
  "motion-hover rounded-control px-2 py-1 text-meta text-secondary hover:bg-hover hover:text-primary";

export default function SlotExplainer({
  slot,
  generatorName,
  tz,
  onSkipOnce,
  onSkipFuture,
  onPin,
  onReset,
  onClose,
}: SlotExplainerProps) {
  const trace = slot.trace ?? [];

  return (
    <div
      role="dialog"
      aria-label="Why this slot is here"
      className="scrim fixed inset-0 z-50 flex items-center justify-center"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) onClose();
      }}
      onKeyDown={(event) => {
        if (event.key === "Escape") {
          event.preventDefault();
          onClose();
        }
      }}
    >
      <div className="flex w-96 flex-col gap-3 rounded-panel border border-line bg-elevated p-3">
        <div className="flex flex-col gap-1">
          <span className="text-title text-primary">
            {slot.intent.platform ?? slot.intent.kind}, {formatTime(slot.startUtc, tz)}
          </span>
          <span className="text-meta text-tertiary">
            {`Generated by "${generatorName}" v${slot.generatorVersion}, layer ${slot.layer}`}
          </span>
        </div>

        {trace.length === 0 ? (
          <span className="text-meta text-tertiary">
            No trace was recorded for this slot
          </span>
        ) : (
          <div className="flex flex-col gap-1">
            {trace.map((entry, index) => (
              <div key={index} className="flex items-baseline gap-2">
                <span className="w-20 shrink-0 text-micro uppercase text-tertiary">
                  {entry.stage}
                </span>
                <span className="w-12 shrink-0 text-micro tabular-nums text-secondary">
                  {entry.startUtc === undefined ? "" : formatTime(entry.startUtc, tz)}
                </span>
                <span className="min-w-0 flex-1 text-micro text-tertiary">
                  {entry.detail}
                </span>
              </div>
            ))}
          </div>
        )}

        <div className="flex flex-wrap items-center gap-1 border-t border-hair pt-2">
          <button type="button" className={ACTION} onClick={onSkipOnce}>
            Skip once
          </button>
          <button type="button" className={ACTION} onClick={onSkipFuture}>
            Skip all future
          </button>
          <button type="button" className={ACTION} onClick={onPin}>
            Pin
          </button>
          <button type="button" className={ACTION} onClick={onReset}>
            Reset to rule
          </button>
        </div>
      </div>
    </div>
  );
}
