/* Generates the 50,000 block fixture used to verify the range query budget in
 * PLAN phase 4. Writes SQL rather than touching a database, so the same file
 * can be applied by the Rust benchmark, by a SQLite browser, or by hand.
 *
 *   node scripts/seed.mjs [count] [outfile]
 */
import { writeFileSync } from "node:fs";

const COUNT = Number.parseInt(process.argv[2] ?? "50000", 10);
const OUT = process.argv[3] ?? "scripts/seed-blocks.sql";
const BATCH = 500;

const KINDS = ["task", "post", "event", "focus", "deadline", "note"];
const CATEGORIES = ["build", "content", "admin", "personal", "deadline"];
const STATUSES = ["open", "in_progress", "done", "cancelled"];

/* Deterministic, so a rerun produces a byte identical file and a rerun of the
   benchmark measures the same data. */
let state = 0x2f6e2b1;
function nextRandom() {
  state ^= state << 13;
  state ^= state >>> 17;
  state ^= state << 5;
  return Math.abs(state) / 2 ** 31;
}

function pick(list) {
  return list[Math.floor(nextRandom() * list.length) % list.length];
}

const HEX = "0123456789abcdef";
function uuidv7(ms, counter) {
  const time = ms.toString(16).padStart(12, "0");
  const rand = Array.from({ length: 16 }, () => HEX[Math.floor(nextRandom() * 16)]).join("");
  const seq = counter.toString(16).padStart(3, "0").slice(-3);
  return `${time.slice(0, 8)}-${time.slice(8, 12)}-7${seq}-8${rand.slice(0, 3)}-${rand.slice(3, 15)}`;
}

// Ten years of blocks either side of a fixed anchor, so range queries have to
// discriminate rather than scanning a narrow band.
const ANCHOR = Date.UTC(2026, 0, 1);
const SPAN_MS = 10 * 365 * 24 * 60 * 60 * 1000;

const lines = [
  "-- Generated by scripts/seed.mjs. Do not edit.",
  "PRAGMA foreign_keys = OFF;",
];

let index = 0;
while (index < COUNT) {
  const rows = [];
  for (let inBatch = 0; inBatch < BATCH && index < COUNT; inBatch += 1, index += 1) {
    const start = ANCHOR + Math.floor(nextRandom() * SPAN_MS) - SPAN_MS / 2;
    const duration = (15 + Math.floor(nextRandom() * 12) * 15) * 60 * 1000;
    const id = uuidv7(start, index);
    rows.push(
      `('${id}','${pick(KINDS)}','Seed block ${index}',NULL,${start},${start + duration},` +
        `'Europe/Rome',0,'${pick(STATUSES)}','${pick(CATEGORIES)}',NULL,NULL,NULL,'{}',${index},` +
        `${start},${start},NULL,NULL,'000000000000000:00000:seed','seed')`,
    );
  }
  lines.push(
    "INSERT INTO blocks (id,kind,title,description,start_utc,end_utc,tz,all_day,status," +
      "category,project_id,parent_id,rrule,payload,sort_order,created_utc,updated_utc," +
      "completed_utc,deleted_utc,hlc,device_id) VALUES\n" +
      rows.join(",\n") +
      ";",
  );
}

lines.push("PRAGMA foreign_keys = ON;");
writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`wrote ${COUNT} blocks to ${OUT}`);
